export default function PrivacyPage() {
  return <div className="page"><div className="shell narrow">
    <header className="page-heading"><span className="eyebrow">Your privacy</span><h1>Heart Mobile Privacy Policy</h1><p>Last updated September 5, 2026</p></header>
    <div className="policy">
      <section><h2>Financial and Payment Information</h2><p>Heart Mobile does not retain customers&apos; full payment card numbers or card security codes. Payments are processed through Stripe, our third-party payment processor. Payment information required to complete a transaction is processed by Stripe in accordance with its applicable security and privacy practices. Heart Mobile receives information necessary to confirm and administer a transaction without maintaining customers&apos; full payment card credentials.</p></section>
      <section><h2>Transaction Records</h2><p>Heart Mobile retains records reasonably necessary for order fulfillment, accounting, customer service, delivery, returns, warranty claims, fraud prevention, and legal compliance. These records may include the products purchased, price and applicable charges, date of purchase, order or transaction number, customer name and contact information, shipping or delivery information, return or warranty information, and payment status or confirmation supplied by our payment processor.</p></section>
      <section><h2>How We Use Information</h2><p>We use information to process and fulfill orders, arrange delivery, communicate about purchases, provide customer support, administer returns and warranties, maintain business and accounting records, prevent fraud, maintain website security, and comply with applicable legal obligations. Heart Mobile does not sell customers&apos; personal information.</p></section>
      <section><h2>Shipping and Service Providers</h2><p>Heart Mobile may provide information reasonably necessary to fulfill an order to shipping carriers, fulfillment partners, suppliers, hosting providers, communications providers, security providers, and other service providers involved in providing our services.</p></section>
      <section><h2>Data Retention and Security</h2><p>Heart Mobile retains transaction and customer information only as long as reasonably necessary for the purposes for which it was collected and applicable business, accounting, warranty, fraud-prevention, and legal requirements. We take reasonable administrative and technical measures designed to protect personal information under our control. Payment card credentials processed by our payment provider are not retained by Heart Mobile.</p></section>
      <section><h2>Your Privacy</h2><p>Customers may contact Heart Mobile regarding personal information associated with their transactions or to request correction of inaccurate information. Requests will be handled in accordance with applicable Canadian privacy laws and legitimate record-retention obligations.</p></section>
      <section><h2>Contact</h2><p>Heart Mobile is operated by <strong>1001123964 Ontario Ltd.</strong><br />28 Broadway Ave, Unit 203<br />Toronto, Ontario M4P 1T5<br />Canada<br /><a href="tel:+14374348683">437-434-8683</a><br /><a href="mailto:john@heartmobile.ca">john@heartmobile.ca</a></p></section>
    </div>
  </div></div>;
}
